//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeersForAyuda {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeersForAyuda.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIKey.
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIUrl.
        /// </summary>
        internal static string APIUrl {
            get {
                return ResourceManager.GetString("APIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppendToFile.
        /// </summary>
        internal static string AppendToFile {
            get {
                return ResourceManager.GetString("AppendToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeersForAyuda.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePattern.
        /// </summary>
        internal static string DatePattern {
            get {
                return ResourceManager.GetString("DatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPath.
        /// </summary>
        internal static string LogPathConfigParameter {
            get {
                return ResourceManager.GetString("LogPathConfigParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogPattern.
        /// </summary>
        internal static string LogPattern {
            get {
                return ResourceManager.GetString("LogPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxFileSize.
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string MaxSizeRollBackups {
            get {
                return ResourceManager.GetString("MaxSizeRollBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaticLogFileName.
        /// </summary>
        internal static string StaticLogFileName {
            get {
                return ResourceManager.GetString("StaticLogFileName", resourceCulture);
            }
        }
    }
}
